language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libboost-all-dev g++-4.8 gcc-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
